### YamlMime:ManagedReference
items:
- uid: System.Workflow.Activities.Rules.RuleException
  id: RuleException
  children:
  - System.Workflow.Activities.Rules.RuleException.#ctor
  - System.Workflow.Activities.Rules.RuleException.#ctor(System.String)
  - System.Workflow.Activities.Rules.RuleException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Workflow.Activities.Rules.RuleException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RuleException
  nameWithType: RuleException
  fullName: System.Workflow.Activities.Rules.RuleException
  type: Class
  summary: "表示计算或验证规则导致的所有异常的基类。"
  syntax:
    content: 'public class RuleException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleException.#ctor
  id: '#ctor'
  parent: System.Workflow.Activities.Rules.RuleException
  langs:
  - csharp
  name: RuleException()
  nameWithType: RuleException.RuleException()
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException()
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "初始化的新实例<xref href=&quot;System.Workflow.Activities.Rules.RuleException&quot;></xref>类。"
  remarks: "此构造函数初始化<xref:System.Exception.Message%2A>属性为系统提供的消息的描述错误并将当前系统区域性考虑在内的新实例。</xref:System.Exception.Message%2A>       下表显示<xref:System.Workflow.Activities.Rules.RuleException>.</xref:System.Workflow.Activities.Rules.RuleException>实例的初始属性的值      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|空引用 (`Nothing`在 Visual Basic 中)。 |  |<xref:System.Exception.Message%2A>|系统提供的一个本地化的描述。 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public RuleException ();
    parameters: []
  overload: System.Workflow.Activities.Rules.RuleException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Workflow.Activities.Rules.RuleException
  langs:
  - csharp
  name: RuleException(String)
  nameWithType: RuleException.RuleException(String)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(String)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "初始化的新实例<xref href=&quot;System.Workflow.Activities.Rules.RuleException&quot;></xref>与指定的错误消息的类。"
  remarks: "此构造函数初始化<xref:System.Exception.Message%2A>属性的新实例使用`message`参数。</xref:System.Exception.Message%2A>       下表显示<xref:System.Workflow.Activities.Rules.RuleException>.</xref:System.Workflow.Activities.Rules.RuleException>实例的初始属性的值      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|空引用 (`Nothing`在 Visual Basic 中)。 |  |<xref:System.Exception.Message%2A>|错误消息字符串。 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public RuleException (string message);
    parameters:
    - id: message
      type: System.String
      description: "描述错误的消息。"
  overload: System.Workflow.Activities.Rules.RuleException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Workflow.Activities.Rules.RuleException
  langs:
  - csharp
  name: RuleException(SerializationInfo,StreamingContext)
  nameWithType: RuleException.RuleException(SerializationInfo,StreamingContext)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "初始化的新实例<xref href=&quot;System.Workflow.Activities.Rules.RuleException&quot;></xref>用序列化数据的类。"
  remarks: "在反序列化，以便重建通过流传输的异常对象过程中调用此构造函数。"
  syntax:
    content: protected RuleException (System.Runtime.Serialization.SerializationInfo serializeInfo, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: serializeInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref>它保存关于所引发异常的序列化的对象数据。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>它包含有关源或目标的上下文信息。</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Workflow.Activities.Rules.RuleException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Workflow.Activities.Rules.RuleException
  langs:
  - csharp
  name: RuleException(String,Exception)
  nameWithType: RuleException.RuleException(String,Exception)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(String,Exception)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "初始化的新实例<xref href=&quot;System.Workflow.Activities.Rules.RuleException&quot;></xref>类，使用指定的错误消息和对内部<xref:System.Exception>这是此<xref:System.Exception>。</xref:System.Exception>根源</xref:System.Exception>的引用"
  remarks: "<xref:System.Exception>引发作为以前的直接结果<xref:System.Exception>应包含对前一个异常中的引用<xref:System.Exception.InnerException%2A>属性。</xref:System.Exception.InnerException%2A> </xref:System.Exception> </xref:System.Exception> <xref:System.Exception.InnerException%2A>属性返回相同的值传递到构造函数中，则为空引用 (`Nothing`) 如果<xref:System.Exception.InnerException%2A>属性不提供内部<xref:System.Exception>给构造函数的值。</xref:System.Exception> </xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       下表显示<xref:System.Workflow.Activities.Rules.RuleException>.</xref:System.Workflow.Activities.Rules.RuleException>实例的初始属性的值      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|内部<xref:System.Exception>引用。 |  |<xref:System.Exception.Message%2A>|错误消息字符串。 |</xref:System.Exception.Message%2A> </xref:System.Exception> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public RuleException (string message, Exception ex);
    parameters:
    - id: message
      type: System.String
      description: "描述错误的消息。"
    - id: ex
      type: System.Exception
      description: "<xref:System.Exception>导致当前<xref:System.Exception>.</xref:System.Exception> </xref:System.Exception> 如果`innerException`参数不是 null 引用 (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref>在 Visual Basic 中)，<xref:System.Exception>用于处理内部<xref:System.Exception>.</xref:System.Exception>的 catch 块中引发</xref:System.Exception>当前"
  overload: System.Workflow.Activities.Rules.RuleException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Workflow.Activities.Rules.RuleException.#ctor
  parent: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: RuleException()
  nameWithType: RuleException.RuleException()
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException()
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.String)
  parent: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: RuleException(String)
  nameWithType: RuleException.RuleException(String)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: RuleException(SerializationInfo,StreamingContext)
  nameWithType: RuleException.RuleException(SerializationInfo,StreamingContext)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.String,System.Exception)
  parent: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: RuleException(String,Exception)
  nameWithType: RuleException.RuleException(String,Exception)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(String,Exception)
- uid: System.Workflow.Activities.Rules.RuleException.#ctor*
  parent: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: RuleException
  nameWithType: RuleException.RuleException
